repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
#- repo: https://gitlab.com/pycqa/flake8
#  rev: 3.9.0
#  hooks:
#  - id: flake8
#    additional_dependencies: [flake8-bugbear==21.4.3]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
