settings:
  mode: retraining # training, retraining, inference
  task: follow_line_gazebo # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: dqn # qlearn, dqn, ddpg, ppo
  simulator: gazebo # openai, carla, gazebo, sumo
  environment_set: gazebo_environments # gazebo_environments, carla_environments
  env: simple # simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: f1 # f1, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: hard # simple, medium, hard, test
  states: sp10 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followline_center # followline_center
  framework: TensorFlow # TensorFlow, Pytorch
  recorder_carla_dir:
  total_episodes: 100000
  training_time: 90
  models_dir: "./checkpoints"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  debug_stats: false
  show_monitoring: true
  steps_to_decrease: 30000
  decrease_substraction: 0.01
  decrease_min: 0.03
  reward_params:
    function: linear
    punish_zig_zag_value: 0.5
    punish_ineffective_vel: 0
    beta_1: 0.8

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  dqn:
    retrain_dqn_tf_model_name: "DQN_sp_16x16_LAPCOMPLETED_Max3076_Epoch492_inTime20231218-045917.model"

inference:
  dqn:
    inference_dqn_tf_model_name:

algorithm:
  dqn:
    alpha: 0.9
    gamma: 0.9
    epsilon: 0.99
    epsilon_discount: 0.99
    epsilon_min: 0.01
    model_name: DQN_sp_16x16
    replay_memory_size: 50_000
    min_replay_memory_size: 64
    minibatch_size: 64
    update_target_every: 5
    memory_fraction: 0.20
    buffer_capacity: 100_000
    batch_size: 64

agents:
  f1:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [10]
  sp3:
    0: [5, 15, 22]
  sp5:
    0: [3, 5, 10, 15, 20]
  sp10:
    0: [3, 15, 30, 45, 50, 70, 100, 120, 150, 190]
  spn:
    0: [10]

actions:
  simple:
    0: [3, 0]
    1: [2, 1]
    2: [2, -1]
  medium:
    0: [3, 0]
    1: [2, 1]
    2: [2, -1]
    3: [1, 1.5]
    4: [1, -1.5]
  hard:
    0: [7, 0]
    1: [4, 1,5]
    2: [4, -1,5]
    3: [3, 1]
    4: [3, -1]
    5: [2, 1]
    6: [2, -1]
    7: [1, 0.5]
    8: [1, -0.5]
  test:
    0: [0, 0]

rewards:
  followline_center:
    from_10: 10
    from_02: 2
    from_01: 1
    penal: -100
    min_reward: 5_000
    highest_reward: 100

gazebo_environments:
  simple:
    env_name: F1Env-v0
    circuit_name: simple
    launchfile: simple_circuit.launch
    environment_folder: f1
    robot_name: f1_renault
    model_state_name: f1_renault # f1_renault_multicamera_multilaser
    start_pose: 0 # 0, 1, 2, 3, 4
    alternate_pose: True
    estimated_steps: 5000
    sensor: camera
    save_episodes: 500
    save_every_step: 5
    lap_completed: False
    save_model: True
    save_positions: True
    debug_level: DEBUG
    telemetry: False
    telemetry_mask: False
    plotter_graphic: False
    circuit_positions_set:
      0: [53.462, -41.988, 0.004, 0, 0, 1.57, -1.57]
      1: [53.462, -8.734, 0.004, 0, 0, 1.57, -1.57] #finish line
      2: [39.712, -30.741, 0.004, 0, 0, 1.56, 1.56]
      3: [-6.861, -36.481, 0.004, 0, 0.01, -0.858, 0.613]
      4: [20.043, 37.130, 0.003, 0, 0.103, -1.4383, -1.4383]
    sleep: 0.05
