settings:
  mode: training # training, retraining, inference
  task: follow_lane_carla # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: ddpg # qlearn, dqn, ddpg, ppo
  simulator: carla # openai, carla, gazebo, sumo
  environment_set: carla_environments # gazebo_environments, carla_environments
  env: follow_lane # Town01, simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: auto_carla # auto_carla, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: continuous # slow, fast
  states: sp5 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followlane_center # followline_center, followline_center_v_w_linear
  framework: TensorFlow # TensorFlow, Pytorch
  total_episodes: 500000
  training_time: 72
  models_dir: "./checkpoints"
  recorder_carla_dir: "./recorders"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  debug_stats: false
  show_monitoring: true
  steps_to_decrease: 30000
  decrease_substraction: 0.01
  decrease_min: 0.05
  reward_params:
    function: pow
    punish_zig_zag_value: 1
    punish_ineffective_vel: 1
    beta_1: 0.5

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  ddpg:
    retrain_ddpg_tf_model_name: ""

inference:
  ddpg:
    retrain_ddpg_tf_model_name:

algorithm:
  ddpg:
    gamma: 0.9
    tau: 0.005
    std_dev: 0.2
    model_name: DDPG_Actor_conv2d32x64_Critic_conv2d32x64
    replay_memory_size: 50_000
    memory_fraction: 0.20
    critic_lr: 0.002
    actor_lr: 0.001
    buffer_capacity: 100_000
    batch_size: 64

agents:
  auto_carla:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [40] #TODO
  sp3:
    0: [10, 50, 150]
  sp5:
    0: [ 280, 290, 300, 310, 320 ]
  sp10:
    0: [270, 280, 290, 300, 310, 320, 330, 340, 350, 360]
  spn:
    0: [10]

actions:
  continuous:
    v: [1, 1.5]
    w: [-0.3, 0.3]


rewards:
  followlane_center:

carla_environments:
  follow_lane:
    env_name: CarlaEnv-v0
    town: Town04 #Town01, Town02, Town03, Town04, Town05, Town10HD
    # Town01_Opt, Town02_Opt, Town03_Opt, Town04_Opt, Town05_Opt, Town10HD_Opt
    car: model1
    weather: ClearNoon #dynamic, argparse
    traffic_pedestrians: False
    city_lights: False
    car_lights: False
    estimated_steps: 5000
    save_episodes: 5 # not used in this carla ppo
    save_every_step: 100 # not used in this carla ppo
    init_pose:
    goal_pose:
    filter: vehicle.*
    generation: "2"
    rolename: "hero" #name
    gamma: 2.2 #for camera
    sync: True #syncronous mode or async
    alternate_pose: False
    waypoints_meters: 5 #distance between waypoints in meters
    waypoints_init: 1471 # 6927
    waypoints_target: 959 #961
    waypoints_lane_id: -1
    waypoints_road_id: 8

carla:
  carla_server: localhost
  carla_client: 2000