settings:
  output_dir: "./logs/"
  save_model: True
  save_positions: True
  telemetry: False
  logging_level: info
  mode: inference
  agent: cartpole
  algorithm: programmatic

# TODO make this section optional
actions:
    available_actions:
      simple:

agent:
  cartpole:
    # TODO To be removed
    camera_params:
      witdh: 640
      height: 480

environments:
  env_name: myCartpole-v0
  environment_folder: cartpole
#    runs: 20000
  runs: 100
  full_experimentation_runs: 0
  update_every: 10
  show_every: 1000
  experiments: 20
  random_start_level: 0 # Number between 0 and 1 that indicates the difficulty of the start position
  random_perturbations_level: 0.1 # Number between 0 and 1 that indicates the frequency of the random perturbations
  random_perturbations_level_step: 0.1 # Number between 0 and 1 that indicates the frequency of the random perturbations
  perturbations_intensity_std: 1 # Number between 0 and 1 that indicates the standard deviation of perturbations intensity
  perturbations_intensity_std_step: 2
  initial_pole_angle: 0
  initial_pole_angle_steps: 0.1
  non_recoverable_angle: 0.3 # not applicable when making experiments with init_pole_angle (always 0.2 over the initial)

algorithm:
    # TODO make it complaining just if the relevant parameter for this algorithm is not found

inference:
  # TODO make it complaining just if the relevant parameter for this algorithm is not found